apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathsync-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: mathsync
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
