apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mathsync-metrics
  namespace: mathsync
  labels:
    app: mathsync
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: mathsync
      component: frontend
  
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    
  namespaceSelector:
    matchNames:
    - mathsync
---
